Consider the below code to answer further questions:

import numpy as np: - 

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int). Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

### Answer1 

In [6]:
import numpy as np

list_ = [ 1 , 2 , 3 , 4 , 5 ]

array_list = np.array(object = list_)


In [7]:
type(list_)

list

In [8]:
type(array_list)

numpy.ndarray

### Answer 2

In [26]:
for elements in list_:
    print(type(elements))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [27]:
for elements in array_list:
    print(type(elements))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Answer 3

the np.array() function inferred the data type of the resulting array from the data type of the input list_, which was a Python list object. Since the elements of list_ are all integers, the data type of the resulting array was also integers (numpy.int32 on most systems).

In [2]:
import numpy as np

list_ = [1, 2, 3, 4, 5]

array_list = np.array(object=list_, dtype=int)


for element in list_:
    print(type(element))

for element in array_list:
    print(type(element))


<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Answer 6

In [11]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Answer 5

In [16]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Answer 4

In [18]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [19]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [20]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.shape(num_array)

(2, 3)

In [23]:
np.shape(num_list)

(2, 3)

In [24]:
np.size(num_array)

6

In [25]:
np.size(num_list)

6