### "12_July_Matrix_Operations_Assignment.ipynb"

### Tensorflow Matrix assignment 

**Part 1: Theoretical Question**

1. What are the different data structures used in Tensorflow?. Give some examples.
2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.
3. Describe the process of matrix addition, multiplication, and element wise operations in TensorFlow.

**Part 2: Practical Implementation**

##### Task 1: Creating and Manipulating Matrices

1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A.
2. Create a Gaussian matrix B with dimensions 4X4, using TensorFlow's truncated_normal function. Display the values of matrix B
3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.
4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.
wc Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

##### Task 2: Performing Additional Matrix Operation
1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function. 
2. Calculate the transpose of matrix F and store the result in matrix G.
3. Calculate the element wise exponential of matrix F and store the result in matrix H.
4. Create a matrix I by concatenating matrix F and matrix G horizontally. 
5. Create a matrix J by concatenating matrix F and matrix H vertically.

### Part 1: Theoretical Question

### Q1. What are the different data structures used in Tensorflow?. Give some examples.

TensorFlow, as a deep learning framework, uses several data structures to represent and manipulate data efficiently during the training and inference processes. Here are some of the key data structures used in TensorFlow along with examples:

Tensors:

Tensors are multi-dimensional arrays that represent data in TensorFlow.

Examples:

- Scalar: A 0-dimensional tensor representing a single value (e.g., a single pixel intensity).
- Vector: A 1-dimensional tensor representing a sequence of values (e.g., a single row or column of data).
- Matrix: A 2-dimensional tensor representing tabular data (e.g., an image with height and width).
- Higher-dimensional tensors: Tensors can have more than two dimensions, such as 3D tensors for volumes or 4D tensors for videos.



In [1]:
import tensorflow as tf
scalar = tf.constant(3.14)  # Scalar tensor
vector = tf.constant([1, 2, 3])  # 1D tensor (vector)
matrix = tf.constant([[1, 2], [3, 4]])  # 2D tensor (matrix)


In [2]:
scalar

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [3]:
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [4]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Variables:

Variables are tensors with values that can be updated or changed during training. They are commonly used for model parameters like weights and biases.

Example:

In [5]:
import tensorflow as tf
weight_matrix = tf.Variable(tf.random.normal((10, 10)))  # Variable representing a weight matrix
weight_matrix

<tf.Variable 'Variable:0' shape=(10, 10) dtype=float32, numpy=
array([[ 0.23326708, -1.2483481 ,  0.70187837,  0.31343263, -0.33701044,
         0.67661196, -0.10024985,  0.34253088, -1.1299161 , -1.8838545 ],
       [-0.38650948,  0.9020241 ,  0.7997566 , -1.1838    , -1.2776661 ,
        -1.9623892 ,  2.142799  , -0.30799437, -0.44662058,  0.18643993],
       [ 1.5654635 ,  1.3713908 , -0.49958214,  1.0189266 ,  0.5297267 ,
         0.1028422 ,  1.8547113 , -0.9637146 ,  0.08446245,  1.537444  ],
       [-0.03474915,  0.3616112 , -0.3282525 , -1.4495802 ,  0.948751  ,
        -1.5073907 , -0.93689376, -0.58908474,  0.18416043, -0.6260623 ],
       [-0.3432828 ,  0.32783294,  0.89316803, -2.10116   , -0.57387817,
        -0.2852402 ,  0.38890126,  1.5645528 ,  0.6780549 ,  2.0104368 ],
       [ 0.11990689, -0.27471623,  1.9910253 ,  0.05357319, -0.25196332,
        -2.4044955 ,  0.5106558 , -0.13053401,  1.2061714 , -0.34713933],
       [-0.13206731, -0.16250335,  0.13141169, -0.57435

### Sparse Tensors:

Sparse tensors represent tensors with a large number of zero values efficiently, useful for tasks like natural language processing.

Example:

In [6]:
import tensorflow as tf
values = [1, 2, 0, 0, 3, 0]
indices = [[0, 0], [0, 1], [1, 0], [2, 1], [3, 2], [3, 3]]
shape = [4, 4]
sparse_tensor = tf.SparseTensor(indices=indices, values=values, dense_shape=shape)
sparse_tensor

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [1 0]
 [2 1]
 [3 2]
 [3 3]], shape=(6, 2), dtype=int64), values=tf.Tensor([1 2 0 0 3 0], shape=(6,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

### Ragged Tensors:

Ragged tensors represent sequences of varying lengths efficiently, often used in natural language processing tasks where sentences have different numbers of words.

Example:

In [7]:
import tensorflow as tf
ragged_tensor = tf.ragged.constant([[1, 2], [3, 4, 5], [6]])
ragged_tensor

<tf.RaggedTensor [[1, 2], [3, 4, 5], [6]]>

### String Tensors:

String tensors represent textual data.

Example:

In [8]:
import tensorflow as tf
string_tensor = tf.constant("Hello, TensorFlow!")
string_tensor

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, TensorFlow!'>

###  Creating a TensorArray

In [9]:

ta = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)
ta

### Dataset:

The tf.data.Dataset API is used to represent and work with large datasets efficiently. It allows for data loading, batching, shuffling, and other data manipulation operations.

### Q2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.


Both TensorFlow constants and variables are fundamental data structures, but they have different purposes and behaviors within a TensorFlow computation graph.

### TensorFlow Constants:

Constants are tensors with fixed values that remain unchanged throughout the computation.
They are typically used to provide inputs or fixed values to the computation graph.
Constants cannot be modified or updated after they are created.

### TensorFlow Variables:

Variables are tensors that hold mutable state, often used for model parameters that need to be learned during training.
They are initialized with initial values and can be updated through operations like assignments.
Variables can be used to store and update values as the model iteratively adjusts its parameters during training.
Let's illustrate the difference with examples:

#### Example of Tensorflow constant 


In [10]:
import tensorflow as tf

# Creating a constant
a = tf.constant(5)

# Attempting to assign a new value to a constant will result in an error
try:
    a.assign(8)  # This will raise an error
except Exception as e:
    print("Error:", e)

Error: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'


### Example of tensorflow variable 

In [11]:
import tensorflow as tf

# Creating a variable with an initial value
initial_value = tf.random.normal(shape=(3, 3))
b = tf.Variable(initial_value)

print("Initial 'b':",b)

# Assigning a new value to the variable using the assign() operation
new_value = tf.random.normal(shape=(3, 3))
b.assign(new_value)

# Now 'b' holds the new value assigned to it
print("\nUpdated 'b':", b)

Initial 'b': <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.9771478 ,  1.1732724 , -1.5948296 ],
       [-0.519507  , -0.22827747,  1.7651294 ],
       [-0.06060474, -0.19110289,  1.6960577 ]], dtype=float32)>

Updated 'b': <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.50593764, -1.2671136 , -0.4444674 ],
       [ 0.02567498,  0.05714185,  0.7929467 ],
       [-1.2507179 ,  0.9868355 ,  0.08074746]], dtype=float32)>


#### In the second example, you can see that a TensorFlow variable b is created with an initial value. Unlike constants, variables can be assigned new values using the assign() operation. This capability is crucial during the training process, where model parameters (weights and biases) are updated iteratively to minimize the loss function.
#### In summary, constants are used to provide fixed inputs or values, while variables are used to hold and update mutable state, often representing model parameters.


### Q3. Describe the process of matrix addition, multiplication, and element wise operations in TensorFlow.

#### Matrix Addition:
Matrix addition is a basic arithmetic operation where corresponding elements of two matrices are added together to create a new matrix of the same dimensions. In TensorFlow, you can perform matrix addition using the tf.add() function or by using the + operator.

In [12]:
import tensorflow as tf

# Define two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[2, 4], [6, 8]])

# Perform matrix addition
result = tf.add(matrix_a, matrix_b)

# Alternatively, you can use the + operator
result_alternative = matrix_a + matrix_b

print("Matrix Addition Result:")
print(result.numpy())
print(result_alternative.numpy())

Matrix Addition Result:
[[ 3  6]
 [ 9 12]]
[[ 3  6]
 [ 9 12]]


### 2. Matrix Multiplication:
Matrix multiplication is a more complex operation where the dot product of rows and columns of two matrices results in a new matrix. TensorFlow provides the tf.matmul() function to perform matrix multiplication.

In [13]:
import tensorflow as tf

# Define two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
result = tf.matmul(matrix_a, matrix_b)

print("Matrix Multiplication Result:")
print(result.numpy())

Matrix Multiplication Result:
[[19 22]
 [43 50]]


### 3. Element-wise Operations:
Element-wise operations involve applying an operation to each corresponding element of two matrices (or a matrix and a scalar). TensorFlow allows you to perform a variety of element-wise operations, such as addition, subtraction, multiplication, division, and more.

In [14]:
import tensorflow as tf

# Define a matrix and a scalar
matrix = tf.constant([[1, 2], [3, 4]])
scalar = 2

# Perform element-wise addition
result_add = matrix + scalar

# Perform element-wise multiplication
result_multiply = matrix * scalar

print("Element-wise Addition Result:")
print(result_add.numpy())

print("Element-wise Multiplication Result:")
print(result_multiply.numpy())

Element-wise Addition Result:
[[3 4]
 [5 6]]
Element-wise Multiplication Result:
[[2 4]
 [6 8]]


### Part 2:

#### Task 1: Creating and Manipulating Matrices

### Q1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A.

In [15]:
import tensorflow as tf

#create a 3X3 matrix with random values from the normal distribution
A = tf.random.normal(shape=(3,3))

#display the value of matrix A
print("Matrix A:")
print(A)

Matrix A:
tf.Tensor(
[[-0.1992763   0.8554451  -1.0981084 ]
 [-1.6360607   0.7261765   0.36278948]
 [-0.7939922   1.398413   -0.5483921 ]], shape=(3, 3), dtype=float32)


### Q2. Create a Gaussian matrix B with dimensions 4X4, using TensorFlow's truncated_normal function. Display the values of matrix B


In [16]:
import tensorflow as tf

#defining the dimension of the matrix 
matrix_shape = (4,4)

#create a 3X3 matrix with random values from the normal distribution
B = tf.random.truncated_normal(shape=matrix_shape, mean=0, stddev=1)

#display the value of matrix B
print("Matrix B:")
print(B)

Matrix B:
tf.Tensor(
[[ 3.4147945e-01 -2.0173238e-01  5.8563106e-02  1.2361519e+00]
 [-2.1893007e-01 -2.0711002e-01  4.5117679e-01 -5.3536451e-01]
 [-3.0158463e-01  1.4549143e+00 -7.6350170e-01  4.4802502e-01]
 [ 1.6967413e-01  6.7660940e-01  6.1771669e-04 -6.6405284e-01]], shape=(4, 4), dtype=float32)


### 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.


In [17]:
import tensorflow as tf


# Generate a Gaussian matrix using normal distribution
mean = 3.0
stddev = 0.5
C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)

# Display the generated matrix
print("Matrix C:")
print(C.numpy())

Matrix C:
[[2.7967207 2.4107368]
 [2.6862166 3.5305285]]


### Q4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.



#### Since, Matrix A has shape (3,3) while matrix B has shape(4,4) it is not possible to add these matrices as shapes are different


In [18]:

matrix1 = tf.random.normal(shape=(2,2))
matrix2 = tf.random.normal(shape=(2,2))
D = tf.add(matrix1, matrix2)

print(f'Matrix 1 :\n {matrix1}')
print(f'\nMatrix 2 :\n {matrix2}')
print(f'\nMatrix D :\n {D}')


Matrix 1 :
 [[ 1.2093607  -1.6177379 ]
 [-0.18402678  0.92993397]]

Matrix 2 :
 [[-0.272253    0.05691211]
 [ 0.2294071  -0.32921347]]

Matrix D :
 [[ 0.9371077  -1.5608258 ]
 [ 0.04538032  0.6007205 ]]


### Q5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [19]:
E = tf.matmul(C,D)

print(f'Matrix C :\n{C}')
print(f'\nMatrix D :\n{D}')
print(f'\nMatrix E = CxD:\n{E}')

Matrix C :
[[2.7967207 2.4107368]
 [2.6862166 3.5305285]]

Matrix D :
[[ 0.9371077  -1.5608258 ]
 [ 0.04538032  0.6007205 ]]

Matrix E = CxD:
[[ 2.7302284 -2.9170148]
 [ 2.6774907 -2.071855 ]]


In [20]:
E = tf.matmul(C,D)

print(f'Matrix C :\n{C.numpy()}')
print(f'\nMatrix D :\n{D.numpy()}')
print(f'\nMatrix E = CxD:\n{E.numpy()}')

Matrix C :
[[2.7967207 2.4107368]
 [2.6862166 3.5305285]]

Matrix D :
[[ 0.9371077  -1.5608258 ]
 [ 0.04538032  0.6007205 ]]

Matrix E = CxD:
[[ 2.7302284 -2.9170148]
 [ 2.6774907 -2.071855 ]]


##### Task 2: Performing Additional Matrix Operation
### Q1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function. 


In [21]:
# Create a matrix F
F = tf.random.uniform(shape=(2,2))
print(f'Matrix F :\n{F}')

Matrix F :
[[0.5483893  0.27799976]
 [0.552814   0.8412311 ]]


### Q2. Calculate the transpose of matrix F and store the result in matrix G.


In [22]:
# Transpose the F matrix
G = tf.transpose(F)

# Print the matrix
print(f'Matrix G :\n{G.numpy()}')

Matrix G :
[[0.5483893  0.552814  ]
 [0.27799976 0.8412311 ]]


In [23]:
print(f'Matrix G :\n{tf.transpose(F)}')

Matrix G :
[[0.5483893  0.552814  ]
 [0.27799976 0.8412311 ]]


### Q3. Calculate the element wise exponential of matrix F and store the result in matrix H.


In [24]:
# Element wise exponent
H = tf.math.exp(F)

# Print matrix H
print(f'Matrix H :\n{H.numpy()}')

Matrix H :
[[1.7304635 1.3204858]
 [1.7381372 2.3192203]]


### Q4. Create a matrix I by concatenating matrix F and matrix G horizontally. 


In [25]:
# Concatenate matrices F and G horizontally to create matrix I
I = tf.concat([F, G], axis=1)

# Display the original matrices and the concatenated matrix
print("Matrix F:")
print(F.numpy())

print("\nMatrix G:")
print(G.numpy())

print("\nMatrix I (Concatenated Horizontally):")
print(I.numpy())

Matrix F:
[[0.5483893  0.27799976]
 [0.552814   0.8412311 ]]

Matrix G:
[[0.5483893  0.552814  ]
 [0.27799976 0.8412311 ]]

Matrix I (Concatenated Horizontally):
[[0.5483893  0.27799976 0.5483893  0.552814  ]
 [0.552814   0.8412311  0.27799976 0.8412311 ]]


###  Q5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [26]:
# Concatenate matrices F and H vertically to create matrix J
J = tf.concat([F, H], axis=0)

# Display the original matrices and the concatenated matrix
print("Matrix F:")
print(F.numpy())

print("\nMatrix H:")
print(H.numpy())

print("\nMatrix J (Concatenated Vertically):")
print(J.numpy())

Matrix F:
[[0.5483893  0.27799976]
 [0.552814   0.8412311 ]]

Matrix H:
[[1.7304635 1.3204858]
 [1.7381372 2.3192203]]

Matrix J (Concatenated Vertically):
[[0.5483893  0.27799976]
 [0.552814   0.8412311 ]
 [1.7304635  1.3204858 ]
 [1.7381372  2.3192203 ]]


In [27]:
T = tf.concat([F, H], axis=1)
print(T.numpy())

[[0.5483893  0.27799976 1.7304635  1.3204858 ]
 [0.552814   0.8412311  1.7381372  2.3192203 ]]
