Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.

Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.

Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.

Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.

Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.

Q6. Implement a function to standardise the features before applying KNN classifier.

Q7. Write a Python function to calculate the euclidean distance between two points.

Q8. Write a Python function to calculate the manhattan distance between two points.

### Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.


In [1]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()

In [2]:
X = iris.data
y = iris.target

In [3]:
X.shape, y.shape

((150, 4), (150,))

In [4]:
from sklearn.model_selection import train_test_split
# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.33, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape


((100, 4), (50, 4), (100,), (50,))

### Scaling the X_train and X_test data

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Implement knn base algorithm and Evaluation of base model on test data

In [6]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train, y_train)

y_pred_knn_classifier = knn_classifier.predict(X_test)

### Calculating accuracy score and confusion martix

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print('confusion matrix: ',confusion_matrix(y_test, y_pred_knn_classifier))
print('accuracy score: ',accuracy_score(y_test, y_pred_knn_classifier))
print('classification_report: ',classification_report(y_test, y_pred_knn_classifier))

confusion matrix:  [[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
accuracy score:  0.98
classification_report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



### Model has pretty good score on base knn algorithm

### Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.


In [8]:
name= ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
boston_housing = pd.read_csv(filepath_or_buffer="/Users/aakanksha/My_Codes/data-science-master-course/data/boston_housing.csv",delim_whitespace=True,names=name)
boston_housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX   
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0  \
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [9]:
boston_housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB


In [10]:
boston_housing.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

### No missing values in dataset

### Seperate X and Y

In [11]:
X = boston_housing.drop(labels=['MEDV'], axis=1)
y = boston_housing['MEDV']

### Train Test Split

In [12]:
from sklearn.model_selection import train_test_split
# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape


((404, 13), (102, 13), (404,), (102,))

### Implementing KNN Regressor Algorithm Base model

In [13]:
from sklearn.neighbors import KNeighborsRegressor
knn_regressor = KNeighborsRegressor(n_neighbors=5)
knn_regressor.fit(X_train, y_train)
y_pred_knn_regressor = knn_regressor.predict(X_test)

### Evaluate model on test data

In [14]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# Calculate evaluation metrics
mse = mean_squared_error(y_test, y_pred_knn_regressor)
mae = mean_absolute_error(y_test, y_pred_knn_regressor)
r2 = r2_score(y_test, y_pred_knn_regressor)

# Print the evaluation metrics
print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("R-squared Score:", r2)

Mean Squared Error: 25.860125490196076
Mean Absolute Error: 3.6639215686274507
R-squared Score: 0.6473640882039258


### Model has not a good score on base knn algorithm

### Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.

In [16]:
# load iris dataset

from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)

# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)

# performing feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



### Hyperparameter Tuning

In [17]:
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],  # number of neighbors to consider
    'weights': ['uniform', 'distance'],  # weight function used in prediction
    'metric': ['euclidean', 'manhattan']  # distance metric used
}

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
gscv_iris = GridSearchCV(KNeighborsClassifier(),param_grid=param_grid,scoring='accuracy',cv=5)
gscv_iris.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [19]:
print('best parameters: ',gscv_iris.best_params_)
print('best score: ',gscv_iris.best_score_)

best parameters:  {'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'distance'}
best score:  0.9400000000000001


In [20]:
y_pred_knn_classifier_best = gscv_iris.predict(X_test)
y_pred_knn_classifier_best

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

### Calculating accuracy score and confusion martix

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print('confusion matrix: ',confusion_matrix(y_test, y_pred_knn_classifier_best))
print('accuracy score: ',accuracy_score(y_test, y_pred_knn_classifier_best))
print('classification_report: ',classification_report(y_test, y_pred_knn_classifier_best))

confusion matrix:  [[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
accuracy score:  0.98
classification_report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



### Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.


In [22]:
# load the dataset
name= ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
boston_housing = pd.read_csv(filepath_or_buffer="/Users/aakanksha/My_Codes/data-science-master-course/data/boston_housing.csv",delim_whitespace=True,names=name)

# separate the data
X = boston_housing.drop(labels=['MEDV'], axis=1)
y = boston_housing['MEDV']

# Split the data into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



### Feature scaling

In [23]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train),columns=X_train.columns)
X_test_scaled = pd.DataFrame(scaler.transform(X_test),columns=X_test.columns)

X_train_scaled.head()

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE   
0  1.287702 -0.500320  1.033237 -0.278089  0.489252 -1.428069  1.028015  \
1 -0.336384 -0.500320 -0.413160 -0.278089 -0.157233 -0.680087 -0.431199   
2 -0.403253  1.013271 -0.715218 -0.278089 -1.008723 -0.402063 -1.618599   
3  0.388230 -0.500320  1.033237 -0.278089  0.489252 -0.300450  0.591681   
4 -0.325282 -0.500320 -0.413160 -0.278089 -0.157233 -0.831094  0.033747   

        DIS       RAD       TAX   PTRATIO         B     LSTAT  
0 -0.802173  1.706891  1.578434  0.845343 -0.074337  1.753505  
1  0.324349 -0.624360 -0.584648  1.204741  0.430184 -0.561474  
2  1.330697 -0.974048 -0.602724 -0.637176  0.065297 -0.651595  
3 -0.839240  1.706891  1.578434  0.845343 -3.868193  1.525387  
4 -0.005494 -0.624360 -0.584648  1.204741  0.379119 -0.165787

In [24]:
X_test_scaled.head()

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE   
0 -0.396809 -0.500320 -1.007111 -0.278089 -0.395412  0.141282  0.555916  \
1 -0.400796  1.229499 -0.664391  3.595975 -0.931315  0.623942 -1.275254   
2 -0.395234 -0.500320  2.433163 -0.278089  0.446720 -0.469805  1.081663   
3 -0.396825 -0.500320 -0.025421 -0.278089 -1.220532 -0.354079 -2.172957   
4  0.167084 -0.500320  1.033237 -0.278089  1.331384 -0.026661  0.831307   

        DIS       RAD       TAX   PTRATIO         B     LSTAT  
0 -0.545853 -0.507797 -0.650926 -0.771951  0.428872 -0.481210  
1  0.126565 -0.624360 -0.903989 -0.322703  0.444180 -1.257094  
2 -0.911447 -0.624360  1.849573  0.800418  0.369934  0.790338  
3  0.694876 -0.624360 -0.596698  0.396095  0.378682 -0.976875  
4 -0.676503  1.706891  1.578434  0.845343  0.315043  0.677687

### Creating Base KNN Regressor model and Evaluate Model on test data

In [25]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Create the KNN regressor model
knn_regressor = KNeighborsRegressor(n_neighbors=5)

# Fit the model on the scaled training data
knn_regressor.fit(X_train_scaled    , y_train)

# Make predictions on the scaled test data
y_pred = knn_regressor.predict(X_test_scaled)

# Calculate evaluation metrics
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the evaluation metrics
print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("R-squared Score:", r2)

Mean Squared Error: 20.60552941176471
Mean Absolute Error: 2.5921568627450977
R-squared Score: 0.7190172315709293


### Using feature scaling, we got a better results as compare to previous solution performing without feature scaling. 

### Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.


In [26]:
# import imp. libraries
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# Load the iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Create a KNN classifier with weighted voting
knn = KNeighborsClassifier(weights='distance', n_neighbors=5)

# Fit the model on the training data
knn.fit(X_train, y_train)

# Predict the labels for the test data
y_pred = knn.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print('Classification Report: ', classification_report(y_test,y_pred))



Accuracy: 0.98
Classification Report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



### Q6. Implement a function to standardise the features before applying KNN classifier.


In [27]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import classification_report

def knn_classifier_with_standardization(X, y, n = 5, test_size = 0.2, cv = 5):

    # train test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)

    # feature scaling
    scaler = StandardScaler()
    X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train))
    X_test_scaled = pd.DataFrame(scaler.fit_transform(X_test))

    # KNN base classifier
    knnc = KNeighborsClassifier()
    knnc.fit(X_train_scaled, y_train)

    # Cross validation estimation 
    scores = cross_val_score(knnc, X_train_scaled, y_train, cv=cv,scoring='accuracy')

    # Mean Cross Val Score
    cval_score_mean = np.mean(scores)

    # Test Data Classification Report
    ypred_test = knnc.predict(X_test_scaled)

    print('Classification Report on Test data :\n')
    print(classification_report(y_test, ypred_test))

    return X_train_scaled, X_test_scaled, y_train, y_test, knnc, cval_score_mean

In [28]:
# load cancer dataset

from sklearn.datasets import load_breast_cancer
X, y =load_breast_cancer(return_X_y=True)

# Using the function to evaluate the data
X_train_scaled, X_test_scaled, y_train, y_test, knnc, cval_score_mean = knn_classifier_with_standardization(X,y,n=5,test_size=0.2,cv=5)

Classification Report on Test data :

              precision    recall  f1-score   support

           0       0.95      0.93      0.94        43
           1       0.96      0.97      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [29]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

def knn_classifier_with_standardization(X_train, y_train, X_test, k):
    # Standardize the features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    # Apply KNN classifier
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)
    y_pred = knn.predict(X_test_scaled)
    
    return y_pred

# Load the Breast Cancer dataset
data = load_breast_cancer()
X = data.data
y = data.target

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply KNN classifier with feature standardization
k = 5  # number of neighbors
y_pred = knn_classifier_with_standardization(X_train, y_train, X_test, k)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generate classification report
classification_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(classification_report)


Accuracy: 0.9473684210526315
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        43
           1       0.96      0.96      0.96        71

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114



### Q7. Write a Python function to calculate the euclidean distance between two points.


In [30]:
import math

def euclidean_distance(point1, point2):
    sqaured_diff = [(p1-p2)**2 for p1, p2 in zip(point1, point2)]

    distance = math.sqrt(sum(sqaured_diff))

    return distance

In [31]:
point1 = (2, 3, 4)
point2 = (5, 1, 7)
distance = euclidean_distance(point1, point2)
print("Euclidean distance:", distance)


Euclidean distance: 4.69041575982343


In [32]:
# Verifying distance manually for above points
a = (5-2)**2 + (1-3)**2 + (7-4)**2
a**0.5

4.69041575982343

### Q8. Write a Python function to calculate the manhattan distance between two points.

In [33]:
def manhattan_distance(point1, point2):
    assert len(point1) == len(point2), "Points must have the same dimensions"
    
    distance = 0
    for coord1, coord2 in zip(point1, point2):
        distance += abs(coord1 - coord2)
    
    return distance


In [34]:
point1 = (2, 3, 4)
point2 = (5, 1, 7)
distance = manhattan_distance(point1, point2)
print(distance)  # Output: 10


8


In [35]:
## Manually calculating manhattan distance
abs(5-2) + abs(1-3) + abs(7-4)

8